// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKOj2OUNITpQjEevYb3iUqL1PbYnjX528',
    appId: '1:987841922201:android:2265d3f38f90ea1cba2408',
    messagingSenderId: '987841922201',
    projectId: 'flutter-application-1-e2362',
    storageBucket: 'flutter-application-1-e2362.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhgXb8HJC6VxwsTj_ShYxXgqtCoyNiPGo',
    appId: '1:987841922201:web:c8c3effaf826949bba2408',
    messagingSenderId: '987841922201',
    projectId: 'flutter-application-1-e2362',
    authDomain: 'flutter-application-1-e2362.firebaseapp.com',
    storageBucket: 'flutter-application-1-e2362.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhgXb8HJC6VxwsTj_ShYxXgqtCoyNiPGo',
    appId: '1:987841922201:web:c8c3effaf826949bba2408',
    messagingSenderId: '987841922201',
    projectId: 'flutter-application-1-e2362',
    authDomain: 'flutter-application-1-e2362.firebaseapp.com',
    storageBucket: 'flutter-application-1-e2362.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA29Rlv-5MPlepREmM0a2AqCDtZ0PCt4CI',
    appId: '1:987841922201:ios:6b596995a99cccb0ba2408',
    messagingSenderId: '987841922201',
    projectId: 'flutter-application-1-e2362',
    storageBucket: 'flutter-application-1-e2362.firebasestorage.app',
    iosBundleId: 'com.realtimechat.app',
  );
}
